version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - bodyclose
    - revive
    - misspell

  settings:
    gosec:
      excludes:
        - G104

issues:
  exclusions:
    rules:
      - path: _test\.go
        linters: [gosec]
